# Generated by Django 5.2.7 on 2025-10-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20251023_1203'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='rides_pickup_time_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='rides_pickup_coords_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['created_at'], name='rides_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_status_idx'),
        ),
    ]
